### ISSUE TITLE
테스트 작성 시 Spec 의 롤백이 되지 않는 현상

### ISSUE THREAD

**Issue by DebugMind** [Friends77/FRI-BACKEND#74]
### 🚨 문제 설명
- `ChatRoomRepositoryKtTest` 에서 생성된 member 가 롤백이 되지 않고 DB 에 남아 있는 문제가 발생했습니다.

### 🧩 예상되는 해결 방안
- (저는 롤백을 하는 테스트에서는 `@Test` 애노테이션을 사용하는게 편리하다고 생각은 합니다..)

### 🛠️ 구현 필요 사항
- 

### 📎 관련 파일/스크린샷
- 테스트 실행 후 DB 를 조회하면 아래와 같이 뜹니다.
```
mydb=# select * from member;
         created_at         | member_id |         updated_at         |     email     |   image_url   | nickname  | oauth2provider | password
----------------------------+-----------+----------------------------+---------------+---------------+-----------+----------------+----------
 2024-12-13 13:45:07.822902 |         1 | 2024-12-13 13:45:07.840719 | test@test.com | test imageurl | test name | GOOGLE         | 1234
(1 row)
```

### 💬 기타 참고 사항
- postgis PR 부분에 kotest 에 관한 코멘트를 남겨놓았는데, 그 부분도 참고해주시면 좋을 것 같아요~

**Comment by lin-chae** [comment]
이거 아직도 똑같나요? datagrip으로 봤을 때, 저는 롤백이 되는 거 같습니다.

**Comment by DebugMind** [comment]
아 저도 이제 롤백이 되네요!! 

테스트 실패하는 것도 SQL 에 문제가 있었네요..
크흠..;; 제가 SQL 을 잘못 짰는데 다른 곳에서 이유를 찾고 있었네요.. 😭
